[package]
name = "rdf-rs"
version = "0.0.1"
edition = "2021"

[[test]]
name = "wright"
path = "src/test.rs"
harness = false

[dependencies]
regex = "1.6"
lazy_static = "1.4"

[dev-dependencies]
wright = { path = "../wright" }
